// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPoRRdWlTZkq8ArQHGe-qqZv_HYtrHIpE',
    appId: '1:380168014762:web:f9753b8033fd1c1362f9d3',
    messagingSenderId: '380168014762',
    projectId: 'moblelad-flutter-firebase',
    authDomain: 'moblelad-flutter-firebase.firebaseapp.com',
    storageBucket: 'moblelad-flutter-firebase.appspot.com',
    measurementId: 'G-V0PNYHHXJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tTRZKL_cNC7sGNz911LGvExq0nGXYrk',
    appId: '1:380168014762:android:d35311a4b27cad4f62f9d3',
    messagingSenderId: '380168014762',
    projectId: 'moblelad-flutter-firebase',
    storageBucket: 'moblelad-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCvAIgDc8-vBuWU3uZU_v7TznrTNk9als',
    appId: '1:380168014762:ios:a0bd5cebdae8c15062f9d3',
    messagingSenderId: '380168014762',
    projectId: 'moblelad-flutter-firebase',
    storageBucket: 'moblelad-flutter-firebase.appspot.com',
    iosClientId: '380168014762-vc9dubh8tpjnnlppg0es6k62j6studv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCvAIgDc8-vBuWU3uZU_v7TznrTNk9als',
    appId: '1:380168014762:ios:a0bd5cebdae8c15062f9d3',
    messagingSenderId: '380168014762',
    projectId: 'moblelad-flutter-firebase',
    storageBucket: 'moblelad-flutter-firebase.appspot.com',
    iosClientId: '380168014762-vc9dubh8tpjnnlppg0es6k62j6studv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );
}
